import { z } from "zod/v4";
export declare const IdSchema: z.ZodUUID;
export type Id = z.infer<typeof IdSchema>;
export declare const TimestampSchema: z.ZodISODateTime;
export type Timestamp = z.infer<typeof TimestampSchema>;
export declare const DateSchema: z.ZodCoercedDate<unknown>;
export type Date = z.infer<typeof DateSchema>;
export declare const PhoneSchema: z.ZodString;
export type Phone = z.infer<typeof PhoneSchema>;
export declare const EmailSchema: z.ZodEmail;
export type Email = z.infer<typeof EmailSchema>;
