export const designTokens = {
    colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        cardForeground: 'var(--card-foreground)',
        popover: 'var(--popover)',
        popoverForeground: 'var(--popover-foreground)',
        primary: 'var(--primary)',
        primaryForeground: 'var(--primary-foreground)',
        primaryHover: 'var(--primary-hover)',
        secondary: 'var(--secondary)',
        secondaryForeground: 'var(--secondary-foreground)',
        secondaryHover: 'var(--secondary-hover)',
        muted: 'var(--muted)',
        mutedForeground: 'var(--muted-foreground)',
        accent: 'var(--accent)',
        accentForeground: 'var(--accent-foreground)',
        accentHover: 'var(--accent-hover)',
        destructive: 'var(--destructive)',
        destructiveForeground: 'var(--destructive-foreground)',
        destructiveHover: 'var(--destructive-hover)',
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        success: 'var(--success)',
        successForeground: 'var(--success-foreground)',
        successHover: 'var(--success-hover)',
        warning: 'var(--warning)',
        warningForeground: 'var(--warning-foreground)',
        warningHover: 'var(--warning-hover)',
        info: 'var(--info)',
        infoForeground: 'var(--info-foreground)',
        infoHover: 'var(--info-hover)',
        chart1: 'var(--chart-1)',
        chart2: 'var(--chart-2)',
        chart3: 'var(--chart-3)',
        chart4: 'var(--chart-4)',
        chart5: 'var(--chart-5)',
        sidebar: 'var(--sidebar)',
        sidebarForeground: 'var(--sidebar-foreground)',
        sidebarPrimary: 'var(--sidebar-primary)',
        sidebarPrimaryForeground: 'var(--sidebar-primary-foreground)',
        sidebarAccent: 'var(--sidebar-accent)',
        sidebarAccentForeground: 'var(--sidebar-accent-foreground)',
        sidebarBorder: 'var(--sidebar-border)',
        sidebarRing: 'var(--sidebar-ring)',
    } as const,

    animation: {
        duration: {
            instant: 'var(--duration-instant)',
            fast: 'var(--duration-fast)',
            normal: 'var(--duration-normal)',
            slow: 'var(--duration-slow)',
            slower: 'var(--duration-slower)',
            slowest: 'var(--duration-slowest)',
        } as const,
        easing: {
            linear: 'var(--ease-linear)',
            in: 'var(--ease-in)',
            out: 'var(--ease-out)',
            'in-out': 'var(--ease-in-out)',
        } as const,
    } as const,
} as const

export type DesignTokens = typeof designTokens

export const colors = designTokens.colors
