/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as protectedCreateOrganizationRouteImport } from './routes/(protected)/create-organization'
import { Route as protectedorganizationRouteRouteImport } from './routes/(protected)/(organization)/route'
import { Route as protectedInviteAcceptRouteImport } from './routes/(protected)/invite/accept'
import { Route as protectedorganizationDashboardRouteImport } from './routes/(protected)/(organization)/dashboard'
import { Route as protectedorganizationTeamOpenhousesIndexRouteImport } from './routes/(protected)/(organization)/team-openhouses/index'
import { Route as protectedorganizationTasksIndexRouteImport } from './routes/(protected)/(organization)/tasks/index'
import { Route as protectedorganizationOpenhouseIndexRouteImport } from './routes/(protected)/(organization)/openhouse/index'
import { Route as protectedorganizationAgentsIndexRouteImport } from './routes/(protected)/(organization)/agents/index'
import { Route as PublicOpenHousesSignInOpenHouseIdRouteImport } from './routes/public/open-houses/sign-in/$openHouseId'
import { Route as protectedorganizationTasksTaskIdRouteImport } from './routes/(protected)/(organization)/tasks/$taskId'
import { Route as protectedorganizationOpenhouseNewRouteImport } from './routes/(protected)/(organization)/openhouse/new'
import { Route as protectedorganizationOpenhouseFormBuilderRouteImport } from './routes/(protected)/(organization)/openhouse/form-builder'
import { Route as protectedorganizationOpenhouseOpenHouseIdRouteImport } from './routes/(protected)/(organization)/openhouse/$openHouseId'
import { Route as protectedorganizationOpenhouseOpenHouseIdIndexRouteImport } from './routes/(protected)/(organization)/openhouse/$openHouseId.index'
import { Route as protectedorganizationOpenhouseOpenHouseIdEditRouteImport } from './routes/(protected)/(organization)/openhouse/$openHouseId.edit'

const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedCreateOrganizationRoute =
  protectedCreateOrganizationRouteImport.update({
    id: '/create-organization',
    path: '/create-organization',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedorganizationRouteRoute =
  protectedorganizationRouteRouteImport.update({
    id: '/(organization)',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedInviteAcceptRoute = protectedInviteAcceptRouteImport.update({
  id: '/invite/accept',
  path: '/invite/accept',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedorganizationDashboardRoute =
  protectedorganizationDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => protectedorganizationRouteRoute,
  } as any)
const protectedorganizationTeamOpenhousesIndexRoute =
  protectedorganizationTeamOpenhousesIndexRouteImport.update({
    id: '/team-openhouses/',
    path: '/team-openhouses/',
    getParentRoute: () => protectedorganizationRouteRoute,
  } as any)
const protectedorganizationTasksIndexRoute =
  protectedorganizationTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => protectedorganizationRouteRoute,
  } as any)
const protectedorganizationOpenhouseIndexRoute =
  protectedorganizationOpenhouseIndexRouteImport.update({
    id: '/openhouse/',
    path: '/openhouse/',
    getParentRoute: () => protectedorganizationRouteRoute,
  } as any)
const protectedorganizationAgentsIndexRoute =
  protectedorganizationAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => protectedorganizationRouteRoute,
  } as any)
const PublicOpenHousesSignInOpenHouseIdRoute =
  PublicOpenHousesSignInOpenHouseIdRouteImport.update({
    id: '/public/open-houses/sign-in/$openHouseId',
    path: '/public/open-houses/sign-in/$openHouseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const protectedorganizationTasksTaskIdRoute =
  protectedorganizationTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => protectedorganizationRouteRoute,
  } as any)
const protectedorganizationOpenhouseNewRoute =
  protectedorganizationOpenhouseNewRouteImport.update({
    id: '/openhouse/new',
    path: '/openhouse/new',
    getParentRoute: () => protectedorganizationRouteRoute,
  } as any)
const protectedorganizationOpenhouseFormBuilderRoute =
  protectedorganizationOpenhouseFormBuilderRouteImport.update({
    id: '/openhouse/form-builder',
    path: '/openhouse/form-builder',
    getParentRoute: () => protectedorganizationRouteRoute,
  } as any)
const protectedorganizationOpenhouseOpenHouseIdRoute =
  protectedorganizationOpenhouseOpenHouseIdRouteImport.update({
    id: '/openhouse/$openHouseId',
    path: '/openhouse/$openHouseId',
    getParentRoute: () => protectedorganizationRouteRoute,
  } as any)
const protectedorganizationOpenhouseOpenHouseIdIndexRoute =
  protectedorganizationOpenhouseOpenHouseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedorganizationOpenhouseOpenHouseIdRoute,
  } as any)
const protectedorganizationOpenhouseOpenHouseIdEditRoute =
  protectedorganizationOpenhouseOpenHouseIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => protectedorganizationOpenhouseOpenHouseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/create-organization': typeof protectedCreateOrganizationRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard': typeof protectedorganizationDashboardRoute
  '/invite/accept': typeof protectedInviteAcceptRoute
  '/openhouse/$openHouseId': typeof protectedorganizationOpenhouseOpenHouseIdRouteWithChildren
  '/openhouse/form-builder': typeof protectedorganizationOpenhouseFormBuilderRoute
  '/openhouse/new': typeof protectedorganizationOpenhouseNewRoute
  '/tasks/$taskId': typeof protectedorganizationTasksTaskIdRoute
  '/public/open-houses/sign-in/$openHouseId': typeof PublicOpenHousesSignInOpenHouseIdRoute
  '/agents/': typeof protectedorganizationAgentsIndexRoute
  '/openhouse/': typeof protectedorganizationOpenhouseIndexRoute
  '/tasks/': typeof protectedorganizationTasksIndexRoute
  '/team-openhouses/': typeof protectedorganizationTeamOpenhousesIndexRoute
  '/openhouse/$openHouseId/edit': typeof protectedorganizationOpenhouseOpenHouseIdEditRoute
  '/openhouse/$openHouseId/': typeof protectedorganizationOpenhouseOpenHouseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/create-organization': typeof protectedCreateOrganizationRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof protectedorganizationDashboardRoute
  '/invite/accept': typeof protectedInviteAcceptRoute
  '/openhouse/form-builder': typeof protectedorganizationOpenhouseFormBuilderRoute
  '/openhouse/new': typeof protectedorganizationOpenhouseNewRoute
  '/tasks/$taskId': typeof protectedorganizationTasksTaskIdRoute
  '/public/open-houses/sign-in/$openHouseId': typeof PublicOpenHousesSignInOpenHouseIdRoute
  '/agents': typeof protectedorganizationAgentsIndexRoute
  '/openhouse': typeof protectedorganizationOpenhouseIndexRoute
  '/tasks': typeof protectedorganizationTasksIndexRoute
  '/team-openhouses': typeof protectedorganizationTeamOpenhousesIndexRoute
  '/openhouse/$openHouseId/edit': typeof protectedorganizationOpenhouseOpenHouseIdEditRoute
  '/openhouse/$openHouseId': typeof protectedorganizationOpenhouseOpenHouseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/error': typeof ErrorRoute
  '/(protected)/(organization)': typeof protectedorganizationRouteRouteWithChildren
  '/(protected)/create-organization': typeof protectedCreateOrganizationRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/': typeof AuthIndexRoute
  '/(protected)/(organization)/dashboard': typeof protectedorganizationDashboardRoute
  '/(protected)/invite/accept': typeof protectedInviteAcceptRoute
  '/(protected)/(organization)/openhouse/$openHouseId': typeof protectedorganizationOpenhouseOpenHouseIdRouteWithChildren
  '/(protected)/(organization)/openhouse/form-builder': typeof protectedorganizationOpenhouseFormBuilderRoute
  '/(protected)/(organization)/openhouse/new': typeof protectedorganizationOpenhouseNewRoute
  '/(protected)/(organization)/tasks/$taskId': typeof protectedorganizationTasksTaskIdRoute
  '/public/open-houses/sign-in/$openHouseId': typeof PublicOpenHousesSignInOpenHouseIdRoute
  '/(protected)/(organization)/agents/': typeof protectedorganizationAgentsIndexRoute
  '/(protected)/(organization)/openhouse/': typeof protectedorganizationOpenhouseIndexRoute
  '/(protected)/(organization)/tasks/': typeof protectedorganizationTasksIndexRoute
  '/(protected)/(organization)/team-openhouses/': typeof protectedorganizationTeamOpenhousesIndexRoute
  '/(protected)/(organization)/openhouse/$openHouseId/edit': typeof protectedorganizationOpenhouseOpenHouseIdEditRoute
  '/(protected)/(organization)/openhouse/$openHouseId/': typeof protectedorganizationOpenhouseOpenHouseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/create-organization'
    | '/auth/login'
    | '/auth/sign-up'
    | '/auth/'
    | '/dashboard'
    | '/invite/accept'
    | '/openhouse/$openHouseId'
    | '/openhouse/form-builder'
    | '/openhouse/new'
    | '/tasks/$taskId'
    | '/public/open-houses/sign-in/$openHouseId'
    | '/agents/'
    | '/openhouse/'
    | '/tasks/'
    | '/team-openhouses/'
    | '/openhouse/$openHouseId/edit'
    | '/openhouse/$openHouseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/error'
    | '/create-organization'
    | '/auth/login'
    | '/auth/sign-up'
    | '/auth'
    | '/dashboard'
    | '/invite/accept'
    | '/openhouse/form-builder'
    | '/openhouse/new'
    | '/tasks/$taskId'
    | '/public/open-houses/sign-in/$openHouseId'
    | '/agents'
    | '/openhouse'
    | '/tasks'
    | '/team-openhouses'
    | '/openhouse/$openHouseId/edit'
    | '/openhouse/$openHouseId'
  id:
    | '__root__'
    | '/'
    | '/(protected)'
    | '/error'
    | '/(protected)/(organization)'
    | '/(protected)/create-organization'
    | '/auth/login'
    | '/auth/sign-up'
    | '/auth/'
    | '/(protected)/(organization)/dashboard'
    | '/(protected)/invite/accept'
    | '/(protected)/(organization)/openhouse/$openHouseId'
    | '/(protected)/(organization)/openhouse/form-builder'
    | '/(protected)/(organization)/openhouse/new'
    | '/(protected)/(organization)/tasks/$taskId'
    | '/public/open-houses/sign-in/$openHouseId'
    | '/(protected)/(organization)/agents/'
    | '/(protected)/(organization)/openhouse/'
    | '/(protected)/(organization)/tasks/'
    | '/(protected)/(organization)/team-openhouses/'
    | '/(protected)/(organization)/openhouse/$openHouseId/edit'
    | '/(protected)/(organization)/openhouse/$openHouseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthIndexRoute: typeof AuthIndexRoute
  PublicOpenHousesSignInOpenHouseIdRoute: typeof PublicOpenHousesSignInOpenHouseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/create-organization': {
      id: '/(protected)/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof protectedCreateOrganizationRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(organization)': {
      id: '/(protected)/(organization)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedorganizationRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/invite/accept': {
      id: '/(protected)/invite/accept'
      path: '/invite/accept'
      fullPath: '/invite/accept'
      preLoaderRoute: typeof protectedInviteAcceptRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(organization)/dashboard': {
      id: '/(protected)/(organization)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedorganizationDashboardRouteImport
      parentRoute: typeof protectedorganizationRouteRoute
    }
    '/(protected)/(organization)/team-openhouses/': {
      id: '/(protected)/(organization)/team-openhouses/'
      path: '/team-openhouses'
      fullPath: '/team-openhouses/'
      preLoaderRoute: typeof protectedorganizationTeamOpenhousesIndexRouteImport
      parentRoute: typeof protectedorganizationRouteRoute
    }
    '/(protected)/(organization)/tasks/': {
      id: '/(protected)/(organization)/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof protectedorganizationTasksIndexRouteImport
      parentRoute: typeof protectedorganizationRouteRoute
    }
    '/(protected)/(organization)/openhouse/': {
      id: '/(protected)/(organization)/openhouse/'
      path: '/openhouse'
      fullPath: '/openhouse/'
      preLoaderRoute: typeof protectedorganizationOpenhouseIndexRouteImport
      parentRoute: typeof protectedorganizationRouteRoute
    }
    '/(protected)/(organization)/agents/': {
      id: '/(protected)/(organization)/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof protectedorganizationAgentsIndexRouteImport
      parentRoute: typeof protectedorganizationRouteRoute
    }
    '/public/open-houses/sign-in/$openHouseId': {
      id: '/public/open-houses/sign-in/$openHouseId'
      path: '/public/open-houses/sign-in/$openHouseId'
      fullPath: '/public/open-houses/sign-in/$openHouseId'
      preLoaderRoute: typeof PublicOpenHousesSignInOpenHouseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/(organization)/tasks/$taskId': {
      id: '/(protected)/(organization)/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof protectedorganizationTasksTaskIdRouteImport
      parentRoute: typeof protectedorganizationRouteRoute
    }
    '/(protected)/(organization)/openhouse/new': {
      id: '/(protected)/(organization)/openhouse/new'
      path: '/openhouse/new'
      fullPath: '/openhouse/new'
      preLoaderRoute: typeof protectedorganizationOpenhouseNewRouteImport
      parentRoute: typeof protectedorganizationRouteRoute
    }
    '/(protected)/(organization)/openhouse/form-builder': {
      id: '/(protected)/(organization)/openhouse/form-builder'
      path: '/openhouse/form-builder'
      fullPath: '/openhouse/form-builder'
      preLoaderRoute: typeof protectedorganizationOpenhouseFormBuilderRouteImport
      parentRoute: typeof protectedorganizationRouteRoute
    }
    '/(protected)/(organization)/openhouse/$openHouseId': {
      id: '/(protected)/(organization)/openhouse/$openHouseId'
      path: '/openhouse/$openHouseId'
      fullPath: '/openhouse/$openHouseId'
      preLoaderRoute: typeof protectedorganizationOpenhouseOpenHouseIdRouteImport
      parentRoute: typeof protectedorganizationRouteRoute
    }
    '/(protected)/(organization)/openhouse/$openHouseId/': {
      id: '/(protected)/(organization)/openhouse/$openHouseId/'
      path: '/'
      fullPath: '/openhouse/$openHouseId/'
      preLoaderRoute: typeof protectedorganizationOpenhouseOpenHouseIdIndexRouteImport
      parentRoute: typeof protectedorganizationOpenhouseOpenHouseIdRoute
    }
    '/(protected)/(organization)/openhouse/$openHouseId/edit': {
      id: '/(protected)/(organization)/openhouse/$openHouseId/edit'
      path: '/edit'
      fullPath: '/openhouse/$openHouseId/edit'
      preLoaderRoute: typeof protectedorganizationOpenhouseOpenHouseIdEditRouteImport
      parentRoute: typeof protectedorganizationOpenhouseOpenHouseIdRoute
    }
  }
}

interface protectedorganizationOpenhouseOpenHouseIdRouteChildren {
  protectedorganizationOpenhouseOpenHouseIdEditRoute: typeof protectedorganizationOpenhouseOpenHouseIdEditRoute
  protectedorganizationOpenhouseOpenHouseIdIndexRoute: typeof protectedorganizationOpenhouseOpenHouseIdIndexRoute
}

const protectedorganizationOpenhouseOpenHouseIdRouteChildren: protectedorganizationOpenhouseOpenHouseIdRouteChildren =
  {
    protectedorganizationOpenhouseOpenHouseIdEditRoute:
      protectedorganizationOpenhouseOpenHouseIdEditRoute,
    protectedorganizationOpenhouseOpenHouseIdIndexRoute:
      protectedorganizationOpenhouseOpenHouseIdIndexRoute,
  }

const protectedorganizationOpenhouseOpenHouseIdRouteWithChildren =
  protectedorganizationOpenhouseOpenHouseIdRoute._addFileChildren(
    protectedorganizationOpenhouseOpenHouseIdRouteChildren,
  )

interface protectedorganizationRouteRouteChildren {
  protectedorganizationDashboardRoute: typeof protectedorganizationDashboardRoute
  protectedorganizationOpenhouseOpenHouseIdRoute: typeof protectedorganizationOpenhouseOpenHouseIdRouteWithChildren
  protectedorganizationOpenhouseFormBuilderRoute: typeof protectedorganizationOpenhouseFormBuilderRoute
  protectedorganizationOpenhouseNewRoute: typeof protectedorganizationOpenhouseNewRoute
  protectedorganizationTasksTaskIdRoute: typeof protectedorganizationTasksTaskIdRoute
  protectedorganizationAgentsIndexRoute: typeof protectedorganizationAgentsIndexRoute
  protectedorganizationOpenhouseIndexRoute: typeof protectedorganizationOpenhouseIndexRoute
  protectedorganizationTasksIndexRoute: typeof protectedorganizationTasksIndexRoute
  protectedorganizationTeamOpenhousesIndexRoute: typeof protectedorganizationTeamOpenhousesIndexRoute
}

const protectedorganizationRouteRouteChildren: protectedorganizationRouteRouteChildren =
  {
    protectedorganizationDashboardRoute: protectedorganizationDashboardRoute,
    protectedorganizationOpenhouseOpenHouseIdRoute:
      protectedorganizationOpenhouseOpenHouseIdRouteWithChildren,
    protectedorganizationOpenhouseFormBuilderRoute:
      protectedorganizationOpenhouseFormBuilderRoute,
    protectedorganizationOpenhouseNewRoute:
      protectedorganizationOpenhouseNewRoute,
    protectedorganizationTasksTaskIdRoute:
      protectedorganizationTasksTaskIdRoute,
    protectedorganizationAgentsIndexRoute:
      protectedorganizationAgentsIndexRoute,
    protectedorganizationOpenhouseIndexRoute:
      protectedorganizationOpenhouseIndexRoute,
    protectedorganizationTasksIndexRoute: protectedorganizationTasksIndexRoute,
    protectedorganizationTeamOpenhousesIndexRoute:
      protectedorganizationTeamOpenhousesIndexRoute,
  }

const protectedorganizationRouteRouteWithChildren =
  protectedorganizationRouteRoute._addFileChildren(
    protectedorganizationRouteRouteChildren,
  )

interface protectedRouteRouteChildren {
  protectedorganizationRouteRoute: typeof protectedorganizationRouteRouteWithChildren
  protectedCreateOrganizationRoute: typeof protectedCreateOrganizationRoute
  protectedInviteAcceptRoute: typeof protectedInviteAcceptRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedorganizationRouteRoute: protectedorganizationRouteRouteWithChildren,
  protectedCreateOrganizationRoute: protectedCreateOrganizationRoute,
  protectedInviteAcceptRoute: protectedInviteAcceptRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedRouteRoute: protectedRouteRouteWithChildren,
  ErrorRoute: ErrorRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthIndexRoute: AuthIndexRoute,
  PublicOpenHousesSignInOpenHouseIdRoute:
    PublicOpenHousesSignInOpenHouseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
