/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as protectedCreateOrganizationRouteImport } from './routes/(protected)/create-organization'
import { Route as protectedorganizationRouteRouteImport } from './routes/(protected)/(organization)/route'
import { Route as protectedorganizationDashboardRouteImport } from './routes/(protected)/(organization)/dashboard'
import { Route as protectedorganizationTasksIndexRouteImport } from './routes/(protected)/(organization)/tasks/index'
import { Route as protectedorganizationTasksTaskIdRouteImport } from './routes/(protected)/(organization)/tasks/$taskId'

const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedCreateOrganizationRoute =
  protectedCreateOrganizationRouteImport.update({
    id: '/create-organization',
    path: '/create-organization',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedorganizationRouteRoute =
  protectedorganizationRouteRouteImport.update({
    id: '/(organization)',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedorganizationDashboardRoute =
  protectedorganizationDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => protectedorganizationRouteRoute,
  } as any)
const protectedorganizationTasksIndexRoute =
  protectedorganizationTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => protectedorganizationRouteRoute,
  } as any)
const protectedorganizationTasksTaskIdRoute =
  protectedorganizationTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => protectedorganizationRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-organization': typeof protectedCreateOrganizationRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard': typeof protectedorganizationDashboardRoute
  '/tasks/$taskId': typeof protectedorganizationTasksTaskIdRoute
  '/tasks/': typeof protectedorganizationTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-organization': typeof protectedCreateOrganizationRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof protectedorganizationDashboardRoute
  '/tasks/$taskId': typeof protectedorganizationTasksTaskIdRoute
  '/tasks': typeof protectedorganizationTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(protected)/(organization)': typeof protectedorganizationRouteRouteWithChildren
  '/(protected)/create-organization': typeof protectedCreateOrganizationRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/': typeof AuthIndexRoute
  '/(protected)/(organization)/dashboard': typeof protectedorganizationDashboardRoute
  '/(protected)/(organization)/tasks/$taskId': typeof protectedorganizationTasksTaskIdRoute
  '/(protected)/(organization)/tasks/': typeof protectedorganizationTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-organization'
    | '/auth/login'
    | '/auth/sign-up'
    | '/auth/'
    | '/dashboard'
    | '/tasks/$taskId'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-organization'
    | '/auth/login'
    | '/auth/sign-up'
    | '/auth'
    | '/dashboard'
    | '/tasks/$taskId'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/(protected)'
    | '/(protected)/(organization)'
    | '/(protected)/create-organization'
    | '/auth/login'
    | '/auth/sign-up'
    | '/auth/'
    | '/(protected)/(organization)/dashboard'
    | '/(protected)/(organization)/tasks/$taskId'
    | '/(protected)/(organization)/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/create-organization': {
      id: '/(protected)/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof protectedCreateOrganizationRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(organization)': {
      id: '/(protected)/(organization)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedorganizationRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(organization)/dashboard': {
      id: '/(protected)/(organization)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedorganizationDashboardRouteImport
      parentRoute: typeof protectedorganizationRouteRoute
    }
    '/(protected)/(organization)/tasks/': {
      id: '/(protected)/(organization)/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof protectedorganizationTasksIndexRouteImport
      parentRoute: typeof protectedorganizationRouteRoute
    }
    '/(protected)/(organization)/tasks/$taskId': {
      id: '/(protected)/(organization)/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof protectedorganizationTasksTaskIdRouteImport
      parentRoute: typeof protectedorganizationRouteRoute
    }
  }
}

interface protectedorganizationRouteRouteChildren {
  protectedorganizationDashboardRoute: typeof protectedorganizationDashboardRoute
  protectedorganizationTasksTaskIdRoute: typeof protectedorganizationTasksTaskIdRoute
  protectedorganizationTasksIndexRoute: typeof protectedorganizationTasksIndexRoute
}

const protectedorganizationRouteRouteChildren: protectedorganizationRouteRouteChildren =
  {
    protectedorganizationDashboardRoute: protectedorganizationDashboardRoute,
    protectedorganizationTasksTaskIdRoute:
      protectedorganizationTasksTaskIdRoute,
    protectedorganizationTasksIndexRoute: protectedorganizationTasksIndexRoute,
  }

const protectedorganizationRouteRouteWithChildren =
  protectedorganizationRouteRoute._addFileChildren(
    protectedorganizationRouteRouteChildren,
  )

interface protectedRouteRouteChildren {
  protectedorganizationRouteRoute: typeof protectedorganizationRouteRouteWithChildren
  protectedCreateOrganizationRoute: typeof protectedCreateOrganizationRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedorganizationRouteRoute: protectedorganizationRouteRouteWithChildren,
  protectedCreateOrganizationRoute: protectedCreateOrganizationRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedRouteRoute: protectedRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
